### ISSUE TITLE
build directory is deleted after starting the server 

### ISSUE THREAD

**Issue by nish1013** [creeperyang/react-seed#1]

**Comment by creeperyang** [comment]
It's just a feature.

If you want to preserve the build directory, 

```js
 "scripts": {
    "start": "npm run clean && npm run serve"
    // change to 
    "start": "npm run serve"
  },
```

**Comment by nish1013** [comment]
I don't see a 'build' folder at all. Where it get created ?

**Comment by creeperyang** [comment]
After run `npm run build`, you will get the `build` dir.

<img width="569" alt="2017-04-07 7 05 34" src="https://cloud.githubusercontent.com/assets/8046480/24797742/38ea33e4-1bc5-11e7-887b-66afed2f5356.png">

And you could get more info if you read through `config.js`,`package.json` and `toos/*`.

**Comment by nish1013** [comment]
Thank you , it worked.
